### ISSUE TITLE
Unable to compile the sample ClInterface

### ISSUE THREAD

**Issue by vishal-keshav** [OValery16/TransferCL#2]
There are some dependencies on boost and jpeg-turbo. Although I am trying to ndk-build with crystalX NDK, it does not recognize these. Also, I can see $(call import-module,boost/1.57.0) and $(call import-module,libjpeg/9a) in Android.mk

Any help in this regard?
I have openCL.so and hpp, only things are missing are the above mentioned. If possible, provide a detail description for including all such dependancies.
Thanks.

**Comment by praisonjoshua** [comment]
Hello ! 
Vishal Keshav sir im doing my project in Federated Learning on Android please help in this regar, My App is crashing when i build you file from you repository , My whatsapp no is 9538790077
please help

**Comment by vishal-keshav** [comment]
Hi Josh,
Please pull the forked repo, where I have updated the dataset for app aswell..
Thanks
